DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS
(
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE     VARCHAR(10),
    PRIMARY KEY (USERNAME)
);

INSERT INTO USERS(USERNAME, PASSWORD, ROLE)
VALUES ('admin', '$2a$10$oGRRRzTpmCHaWX0BF78.7.0DA0s16X9voDCFAnS0D9WR2zZ9SR0Dm', 'ROLE_ADMIN');
INSERT INTO USERS(USERNAME, PASSWORD, ROLE)
VALUES ('anna_k', '$2a$10$vAaYjbNAMUmxTt21Q4STCOyPgBcvg1DWpbBx.25WwSyhcjOUOiPk2', 'ROLE_USER');
INSERT INTO USERS(USERNAME, PASSWORD, ROLE)
VALUES ('tomek_nowak', '$2a$10$vAaYjbNAMUmxTt21Q4STCOyPgBcvg1DWpbBx.25WwSyhcjOUOiPk2', 'ROLE_USER');
INSERT INTO USERS(USERNAME, PASSWORD, ROLE)
VALUES ('kasia_w', '$2a$10$vAaYjbNAMUmxTt21Q4STCOyPgBcvg1DWpbBx.25WwSyhcjOUOiPk2', 'ROLE_USER');
INSERT INTO USERS(USERNAME, PASSWORD, ROLE)
VALUES ('j_kowalski', '$2a$10$vAaYjbNAMUmxTt21Q4STCOyPgBcvg1DWpbBx.25WwSyhcjOUOiPk2', 'ROLE_USER');