DROP TABLE IF EXISTS FOLLOW;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID  integer AUTO_INCREMENT,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME  varchar(50) NOT NULL,
    USERNAME   varchar(50) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS FOLLOW
(
    FOLLOW_ID    integer AUTO_INCREMENT,
    FOLLOWER_ID  integer   NOT NULL,
    FOLLOWING_ID integer   NOT NULL,
    CREATE_AT    timestamp NOT NULL,
    PRIMARY KEY (FOLLOW_ID)
);

ALTER TABLE AUTHORS
    ADD CONSTRAINT UK_AUTHORS__USERNAME UNIQUE (USERNAME);

ALTER TABLE FOLLOW
    ADD CONSTRAINT FK_FOLLOW__FOLLOW_ID_TO_AUTHORS FOREIGN KEY (FOLLOWER_ID) REFERENCES AUTHORS (AUTHOR_ID);

ALTER TABLE FOLLOW
    ADD CONSTRAINT FK_FOLLOW__FOLLOWING_ID_TO_AUTHORS FOREIGN KEY (FOLLOWING_ID) REFERENCES AUTHORS (AUTHOR_ID);

INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (999, 'admin', 'admin', 'admin');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1000, 'Anna', 'Kowalska', 'anna_k');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1001, 'Tomasz', 'Nowak', 'tomek_nowak');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1002, 'Katarzyna', 'Wiśniewska', 'kasia_w');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1003, 'Jan', 'Kowalski', 'j_kowalski');
