DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID  integer AUTO_INCREMENT,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME  varchar(50) NOT NULL,
    USERNAME   varchar(50) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
);

ALTER TABLE AUTHORS
    ADD CONSTRAINT UK_AUTHORS__USERNAME UNIQUE (USERNAME);

INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (999, 'admin', 'admin', 'admin');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1000, 'Anna', 'Kowalska', 'anna_k');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1001, 'Tomasz', 'Nowak', 'tomek_nowak');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1002, 'Katarzyna', 'Wiśniewska', 'kasia_w');
INSERT INTO AUTHORS(AUTHOR_ID, FIRST_NAME, LAST_NAME, USERNAME)
VALUES (1003, 'Jan', 'Kowalski', 'j_kowalski');
